export const USER_ACTIONS = {
    LOGIN_USER : 'LOGIN_USER',
    LOGOUT_USER : 'REGISTER_USER',
    UPDATE_USER : 'UPDATE_USER',
    SET_DETAILS : 'SET_DETAILS'
}

export const PRODUCT_ACTIONS = {
    FILL_PRODUCTS : 'FILL_PRODUCTS',
}

export const LOADING_ACTIONS = {
    SET_LOADING_STATE : 'SET_LOADING_STATE'
}