import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HeroImage from '../components/HeroImage';
import OffersComponent from '../components/OffersComponent';
import CategoryPreview from '../components/CategoryPreview';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroImage/>
      <OffersComponent/>
      <CategoryPreview/>
    </>
  )
}
