import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HeroImage from '../components/HeroImage';
import OffersComponent from '../components/OffersComponent';
import CategoryPreview from '../components/CategoryPreview';
import CategoryHome from '../components/ShopByCategory/CategoryHome';
import Sidebar from '../components/Sidebar';
import OrderPrescription from '../components/OrderPrescription';
import DekstopComponents from '../components/DekstopComponents';
import {useState} from 'react';
export default function Home() {

  return (
    <>
   
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroImage/>
      <div className='lg:px-20'>
      <div className='hidden lg:block'>
      <DekstopComponents></DekstopComponents>
      </div>
      <OrderPrescription/>
      <OffersComponent/>
      <CategoryHome/>
      <CategoryPreview heading="Popular Products"/>
      <CategoryPreview heading="Seasonal Products"/>
      </div>


    </>
  )
}
